/**
 * Lista base de contraseñas filtradas, embebida en el código.
 *
 * Son contraseñas **públicas y notorias**: encabezan todos los listados de
 * filtraciones publicados desde hace quince años. Escribirlas acá no revela
 * nada de nadie.
 *
 * Esta lista no reemplaza al archivo grande de ADR-024 (el orden del millón
 * más usado, que mantiene `cicd` y que carga `ArchivoLocalDeContrasenasFiltradas`).
 * Es el piso: lo que el sistema rechaza aunque el archivo no esté cargado,
 * y lo que usa el modo mock para que el alta funcione end to end sin ningún
 * archivo de datos.
 *
 * Incluye a propósito el repertorio local —clubes, equipos, apodos, el DNI
 * escrito como contraseña, "contraseña" con y sin eñe—: una lista armada sólo
 * con las diez mil de un listado en inglés deja pasar `boca1905` y `river1901`,
 * que en Argentina son exactamente el mismo problema.
 */

export const CONTRASENAS_FILTRADAS_BASE: readonly string[] = [
  // ── Las universales ──────────────────────────────────────────────────────
  '123456',
  '123456789',
  '12345678',
  '1234567890',
  '12345',
  '1234567',
  '111111',
  '000000',
  '121212',
  '123123',
  '654321',
  '1q2w3e4r',
  'qwerty',
  'qwerty123',
  'qwertyuiop',
  'asdfghjkl',
  'zxcvbnm',
  '1qaz2wsx',
  'password',
  'password1',
  'password123',
  'Password1',
  'Password123',
  'admin',
  'admin123',
  'administrator',
  'root',
  'letmein',
  'welcome',
  'monkey',
  'dragon',
  'sunshine',
  'iloveyou',
  'princess',
  'football',
  'baseball',
  'starwars',
  'superman',
  'batman',
  'trustno1',
  'whatever',
  'shadow',
  'master',
  'michael',
  'jennifer',
  'jordan23',
  'abc123',
  'abcd1234',
  'a1b2c3d4',
  'test123',
  'temporal',
  'cambiar123',
  'changeme',
  'default',
  'secret',
  'secreto',
  'passw0rd',
  'p@ssw0rd',
  'P@ssw0rd',
  'p@ssword',
  'qazwsx',
  'asdasd',
  'aaaaaa',
  'aaaaaaaa',
  '11111111',
  '00000000',
  '987654321',
  '147258369',
  '159753',
  'zaq12wsx',

  // ── Castellano y repertorio rioplatense ──────────────────────────────────
  'contrasena',
  'contraseña',
  'contrasena1',
  'contraseña1',
  'contrasena123',
  'clave123',
  'miclave',
  'mipassword',
  'holahola',
  'hola1234',
  'holamundo',
  'teamo',
  'teamomucho',
  'tequiero',
  'mamaypapa',
  'familia',
  'mifamilia',
  'micasa',
  'gordita',
  'gordito',
  'bebita',
  'bebito',
  'chiquita',
  'amoramor',
  'principe',
  'princesa',
  'estrella',
  'mariposa',
  'girasol',
  'libertad',
  'esperanza',
  'gracias',
  'argentina',
  'argentina1',
  'argentina2022',
  'arg3ntina',
  'buenosaires',
  'bsas1234',
  'rosario',
  'cordoba',
  'cordoba1',
  'mendoza',
  'laplata',
  'mardelplata',
  'tucuman',
  'patagonia',
  'malvinas',
  'sanmartin',
  'belgrano',
  'independencia',
  'quilmes',
  'lanus',
  'banfield',
  'tigre2024',

  // ── Fútbol: el hueco más grande de cualquier lista en inglés ─────────────
  'boca',
  'bocajuniors',
  'boca1905',
  'bocajrs',
  'vamosboca',
  'river',
  'riverplate',
  'river1901',
  'vamosriver',
  'racing',
  'racing1903',
  'independiente',
  'independiente1905',
  'sanlorenzo',
  'cuervo1908',
  'huracan',
  'velez',
  'newells',
  'central',
  'estudiantes',
  'gimnasia',
  'messi',
  'messi10',
  'lionelmessi',
  'maradona',
  'maradona10',
  'diego10',
  'dieguito',
  'campeones',
  'campeondelmundo',
  'lascarpas',
  'seleccion',
  'albiceleste',

  // ── Música, apodos y cultura popular local ───────────────────────────────
  'charly',
  'spinetta',
  'cerati',
  'sodastereo',
  'losredondos',
  'ricoteros',
  'larenga',
  'callejeros',
  'divididos',
  'lasoliv',
  'gilda',
  'rodrigo',
  'cuarteto',
  'cumbia',
  'mate',
  'materrere',
  'asado',
  'milanesa',
  'dulcedeleche',
  'fernet',
  'fernetconcoca',
  'quilmes1890',
  'facundo',
  'santiago',
  'valentina',
  'martina',
  'sofia',
  'agustin',
  'joaquin',
  'lucia',
  'camila',
  'nicolas',
  'juanperez',
  'jose1234',
  'carlos123',
  'maria123',

  // ── Fechas y documentos escritos como contraseña ─────────────────────────
  '20102010',
  '19901990',
  '19801980',
  '01012000',
  '25051810',
  '09071816',
  '02041982',
  '18121986',
  '18122022',
  '30101983',
  '12345678a',
  '20304050',
  '11223344',
  '10203040',
  'dni12345678',
  'cuit20123456789',

  // ── Marcas del producto: lo primero que prueba cualquiera ────────────────
  'mejorar',
  'mejorar123',
  'Mejorar123',
  'mejorar2026',
  'deuda123',
  'micuenta',
  'micuenta123',
  'usuario',
  'usuario1',
  'usuario123',
  'invitado',
  'prueba',
  'prueba123',
  'demo1234',
];
